### PR TITLE
Feature/upgrade docusaurus

### PR DESCRIPTION
**Pull request by hobadams**
This PR upgrades docusaurus

https://v2.docusaurus.io/docs/migrating-from-v1-to-v2

It doesn't look exactly the same but is very close.

The reason for doing this is we will be using v2 for the cloud docs and it makes sense to have them on the same version.

You can see a preview here - https://brave-meitner-eeebc7.netlify.com/docs/getting-started/intro/

**Important**

Screenshot 2020-02-18 at 16 42 39

To discuss with @cane-lagerwaard & @mateuszwozniak if we should use v2 (it's in Alpha)

### CODE REVIEW

**Comment by cane-lagerwaard** [comment]
Looks like there is a build error on netlify

```
4:51:41 PM: > docusaurus build
4:51:43 PM: Minimum node version not met :)
4:51:43 PM: You are using Node v8.17.0, Requirement: Node >=10.9.0.
4:51:43 PM: npm
4:51:43 PM:  ERR!
4:51:43 PM: code ELIFECYCLE
4:51:43 PM: npm ERR!
4:51:43 PM:  errno 1
4:51:43 PM: npm
4:51:43 PM:  ERR! @ build: `docusaurus build`
4:51:43 PM: npm
4:51:43 PM: ERR! Exit status 1
4:51:43 PM: npm ERR!
4:51:43 PM: npm ERR! Failed at the @ build script.
4:51:43 PM: npm
4:51:43 PM: ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by hobadams** [comment]
> Looks like there is a build error on netlify
> 
> ```
> 4:51:41 PM: > docusaurus build
> 4:51:43 PM: Minimum node version not met :)
> 4:51:43 PM: You are using Node v8.17.0, Requirement: Node >=10.9.0.
> 4:51:43 PM: npm
> 4:51:43 PM:  ERR!
> 4:51:43 PM: code ELIFECYCLE
> 4:51:43 PM: npm ERR!
> 4:51:43 PM:  errno 1
> 4:51:43 PM: npm
> 4:51:43 PM:  ERR! @ build: `docusaurus build`
> 4:51:43 PM: npm
> 4:51:43 PM: ERR! Exit status 1
> 4:51:43 PM: npm ERR!
> 4:51:43 PM: npm ERR! Failed at the @ build script.
> 4:51:43 PM: npm
> 4:51:43 PM: ERR! This is probably not a problem with npm. There is likely additional logging output above.
> ```

@cane-lagerwaard - it looks like we need to update the node version within Netlify.

**Comment by cane-lagerwaard** [comment]
> > Looks like there is a build error on netlify
> > ```
> > 4:51:41 PM: > docusaurus build
> > 4:51:43 PM: Minimum node version not met :)
> > 4:51:43 PM: You are using Node v8.17.0, Requirement: Node >=10.9.0.
> > 4:51:43 PM: npm
> > 4:51:43 PM:  ERR!
> > 4:51:43 PM: code ELIFECYCLE
> > 4:51:43 PM: npm ERR!
> > 4:51:43 PM:  errno 1
> > 4:51:43 PM: npm
> > 4:51:43 PM:  ERR! @ build: `docusaurus build`
> > 4:51:43 PM: npm
> > 4:51:43 PM: ERR! Exit status 1
> > 4:51:43 PM: npm ERR!
> > 4:51:43 PM: npm ERR! Failed at the @ build script.
> > 4:51:43 PM: npm
> > 4:51:43 PM: ERR! This is probably not a problem with npm. There is likely additional logging output above.
> > ```
> 
> @cane-lagerwaard - it looks like we need to update the node version within Netlify.

Yes, we could add a `.node_version` file to the root folder 
https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript

**Comment by cane-lagerwaard** [comment]
Some things seem to have been broken, for instance when I click on the logo on the top left I'm getting a 404. We should properly test the links/pages to see what's broken before merging

**Pull request closed without merging**
